# Generated by Django 4.2.5 on 2023-10-17 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="quote",
        ),
    ]
